### ISSUE TITLE
Use node-sass for building

### ISSUE THREAD

**Issue by cherifGsoul** [stealjs/steal-sass#10]
I suggest to use [node-sass](https://www.npmjs.com/package/node-sass) for builiding, it is based on libsass (written in C++) which is incredibly fast

**Comment by matthewp** [comment]
Yeah, we should definitely do this.

**Comment by leoj3n** [comment]
Just curious: Was there a technical or design reason that sass.js was chosen instead of using node-sass to begin with?

**Comment by DesignByOnyx** [comment]
Live reload will compile sass in the browser, which is what sass.js allows. We've come to realize that this is slow and inefficient and are working on a better solution.

**Comment by matthewp** [comment]
@leoj3n Steal is a browser loader :)  A steal plugin that doesn't run in the browser doesn't make a lot of sense. If you want to use node-sass... then just use node-sass, there doesn't need to be any steal plugin for that. :)

**Comment by leoj3n** [comment]
Thank you both for your prompt responses!

If I understand correctly, `node-sass` will be utilized for local development while `sass.js` will be utilized when a client loads up the app. It seems like kind of an anti-pattern to use **pre**processors on the client to process `less` or `sass` every time a client loads up the app, so I'm going to take @matthewp's advice and just compile the css outside of steal like `node-sass --watch src/styles.scss src/styles.css` and then include the style like `<can-import from="my-app/styles.css!" />` so it will be autoloaded. Thanks.

**Comment by matthewp** [comment]
@leoj3n That's a fine approach, in this case.

To be clear, steal-sass doesn't preprocess every time a client loads up the app in production.  When you perform a build everything is compiled to css and bundled and that is what is loaded in production, steal-sass is not used at all.

**Comment by leoj3n** [comment]
@matthewp Ah, that's good to know that the assets would be compiled! I noticed the `<can-import />` still existing in the production HTML, and naively assumed that was being used still to render the page.

**Comment by frank-dspeed** [comment]
This can be Closed i think i made steal-sass running again using sass.js and thats fine because thats what its expected to do as @matthewp pointed out node-sass can be added to the build chain as well.
