### ISSUE TITLE
Possible bug if you have more than one scss file in your project

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-sass#3]
https://github.com/stealjs/steal-sass/blob/master/main.js#L66

**Comment by Lighttree** [comment]
Hi @matthewp just would like to clarify is this bug related to case when you have one main `scss` file that imports others ?

For example I do import `<can-import from="myApp/assets/styles/styles.scss!" />`
And `styles.scss` has something like:

```
@import "atoms/_variables.scss";
@import "atoms/_normalize.scss";
@import "bourbon";
@import "atoms/_grid-settings.scss";
@import "atoms/neat/neat";
```

As a result I have all these "imports" as plain text and uncompiled. I've checked the same approach with `Less` and it works. Not sure does it makes sense to open new issue for that ?

**Comment by matthewp** [comment]
@Lighttree Sure, open a new issue. Just so you know, this project is still "alpha" quality and doesn't have the work put into it that less does. If you'd like to contribute that would be good.

**Comment by Lighttree** [comment]
@matthewp I've opened new issue: #9  I'll have a look to how it works and if I'll be able to help with this I'll let you know.

**Comment by cherifGsoul** [comment]
is this corrected?
